language: go

go:
  - "1.14.x"

branches:
  only:
    - master
    - dev
env:
  - GO111MODULE=on

install: true

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

script:
  - go vet ./...
  - golangci-lint run
  - go test ./...
